version: "3.7"

services:
    script:
        build: .
        image: sanarisan/excel-filler:1
        restart: always
        command: >
            sh -c "yarn wipe-cli &&
                yarn launch-prod"
